apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qbittorrent
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "qbittorrent/**.yml"
  template:
    metadata:
      name: '{{name}}-qbittorrent'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://k8s-at-home.com/charts
        targetRevision: "13.5.2"
        chart: qbittorrent

      destination:
        server: '{{address}}'
        namespace: cloud

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
