apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-cr
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "cert-manager-cr/**.yml"
  template:
    metadata:
      name: '{{name}}-cert-manager-cr'
    spec:
      project: default
      source:
        helm:
          releaseName: cert-manager-cr
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        targetRevision: HEAD
        path: "cert-manager-cr/resources"

      destination:
        server: '{{address}}'
        namespace: cert-manager

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
