apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: srcds-css-ze
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "argocd/css-ze/**.yml"
  template:
    metadata:
      name: '{{name}}-srcds-css-ze'
    spec:
      project: default
      source:
        helm:
          releaseName: srcds-css-ze
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://srcdslab.github.io/helm-charts
        targetRevision: "0.0.3"
        chart: srcds

      destination:
        server: '{{address}}'
        namespace: srcds-css-ze

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
