apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openebs
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "openebs/**.yml"
  template:
    metadata:
      name: '{{name}}-openebs'
    spec:
      project: default
      source:
        helm:
          releaseName: openebs
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://openebs.github.io/charts
        targetRevision: "3.7.0"
        chart: openebs

      destination:
        server: '{{address}}'
        namespace: openebs

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
