apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "argocd/sealed-secrets/**.yml"
  template:
    metadata:
      name: '{{name}}-sealed-secrets'
    spec:
      project: default
      source:
        helm:
          releaseName: sealed-secrets
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: "2.9.0"
        chart: sealed-secrets

      destination:
        server: '{{address}}'
        namespace: sealed-secrets

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
