repoServer:
  env:
    - name: ARGOCD_EXEC_TIMEOUT
      value: 10m

server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-letsencrypt
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: "nginx"
    hosts:
      - argocd.krysantem.net
    tls:
      - secretName: argocd.krysantem.net-tls
        hosts:
          - argocd.krysantem.net
    https: true
