apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sftp
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "argocd/sftp/**.yml"
  template:
    metadata:
      name: '{{name}}-sftp'
    spec:
      project: default
      source:
        helm:
          releaseName: sftp
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://emberstack.github.io/helm-charts
        targetRevision: "5.1.5"
        chart: sftp

      destination:
        server: '{{address}}'
        namespace: cloud

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
