apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sftpgo
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "argocd/sftpgo/**.yml"
  template:
    metadata:
      name: '{{name}}-sftpgo'
    spec:
      project: default
      source:
        helm:
          releaseName: sftpgo
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://charts.truecharts.org/
        targetRevision: "2.0.12"
        chart: sftpgo

      destination:
        server: '{{address}}'
        namespace: cloud

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
