apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgAUqo9HpeDvkZjQpaTvOinNFrSECGQ/XpiVQDzVNI3a6aZAs9qoj2uEhiJU/Ukh8ZTt0bxlXOtcIC/RK59TP58M9H0tVSl/8jmFgfF/IVhZ8hOxc7sscvBqGFTvAMAPvBUxZA1GNUbH7bpw7J5NOPPK09aLLs8YzlzI1xy1I3/IcLMjZeRYZClCy1lrFtUFKiXTz4yxnjQ7YgDkJb1qu0Vxhqlk+gwNkjixDO9tJkSkfMiX6L0M73vDXyCO2OUyOUrfGK04j/2iKlayKQ1stOBflqTyilOgMJ2Vn8omdBiq0zP92HMhScLJmz2ILHiFgbilxKhXNKqA/QpJe/OSsK9hkqc8kGIvFiBezbJc/H51MWh8GJ/iM9NB1WeIeZ7gyp7j1f3zQDHg7oZpyh8/BAve6C6NMKs7dWDcFBvIx/hIf+USL1uSWMPrbAlArV+0MMRiUYpU9CzxA3dQioOkk31nono/vSXwK/TiEG3lzfjd52TwktDSJzrMdSmAa71JMHhOG0F9D2c/leaWwmyXrRbme98evdquxgpPYTXkor0HpD9RSvxC7yQM9ArVh5BhvGaKH8OKn4B4J0lCCB7BRDPAG7kjOWdP0pPNUu6Ln1VqtxcjHsOnhrCqXxvtXHZPvRaoqZjhCW4kHT9zmpJw1Ul9YZr7UFvkkCAanw5YVxmvnYl2I9t2wARWfHJwsAfsH2REbbHEeYGaFsT3YTUJT3q3vIRoUVKbzKoVtJn6/vbFMTRtKOVGGp6t
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
    type: Opaque

