apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pydio-mariadb
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "mariadb/**.yml"
  template:
    metadata:
      name: '{{name}}-pydio-mariadb'
    spec:
      project: default
      source:
        helm:
          releaseName: mariadb
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: registry-1.docker.io/bitnamicharts
        targetRevision: "12.2.5"
        chart: mariadb

      destination:
        server: '{{address}}'
        namespace: cloud

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
