apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pydio
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "argocd/pydio/**.yml"
  template:
    metadata:
      name: '{{name}}-pydio'
    spec:
      project: default
      source:
        helm:
          releaseName: pydio
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://charts.truecharts.org
        targetRevision: "7.0.23"
        chart: pydio-cells

      destination:
        server: '{{address}}'
        namespace: cloud

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
