apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "external-dns/**.yml"
  template:
    metadata:
      name: '{{name}}-external-dns'
    spec:
      project: default
      source:
        helm:
          releaseName: external-dns
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: registry-1.docker.io/bitnamicharts
        targetRevision: "6.20.3"
        chart: external-dns

      destination:
        server: '{{address}}'
        namespace: external-dns

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
