name: "in-cluster"
address: "https://kubernetes.default.svc"
values: |
  # -- Application configuration.
  # See the [official documentation](https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md).
  config: {}

  # -- Additional storage [volumes](https://kubernetes.io/docs/concepts/storage/volumes/).
  # See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
  volumes:
    - name: qbittorrent-downloads
      persistentVolumeClaim:
        claimName: qbittorrent-downloads

  # -- Additional [volume mounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/).
  # See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
  volumeMounts:
    - name: qbittorrent-downloads
      mountPath: /home/torrent/downloads

  service:
    # -- Annotations to be added to the service.
    annotations:
      metallb.universe.tf/allow-shared-ip: ingress-nginx

    # -- Kubernetes [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
    type: ClusterIP

    ports:
      sftp:
        # -- SFTP service port.
        port: 2222

        # -- (int) SFTP node port (when applicable).
        nodePort:

  # -- Run pods in the host network of nodes.
  # Warning: The use of host network is [discouraged](https://kubernetes.io/docs/concepts/configuration/overview/#services). Make sure to use it only when absolutely necessary.
  hostNetwork: true
