name: "in-cluster"
address: "https://kubernetes.default.svc"
values: |
  env:
    SFTPGO_COMMON__DEFENDER__ENABLED: "true"
    SFTPGO_SFTPD__BINDINGS__0__PORT: "2222"
    SFTPGO_SFTPD__BINDINGS__0__ADDRESS: "0.0.0.0"
    SFTPGO_HTTPD__BINDINGS__0__PORT: "8888"
    SFTPGO_SFTPD__BINDINGS__0__ADDRESS: "0.0.0.0"
  image:
    pullPolicy: IfNotPresent
    repository: tccr.io/truecharts/sftpgo
    tag: latest@sha256:b1c358cdf3b23b93b038f97646b128d370af0aaa5e4d4ed78790076d144b294f
  persistence:
    backupdirectory:
      enabled: true
      mountPath: /srv/sftpgo/backups
      size: 1Gi
    configpath:
      enabled: true
      mountPath: /var/lib/sftpgo
      size: 1Gi
    data:
      enabled: true
      mountPath: /srv/sftpgo/data
      size: 1Gi
    shareaccess:
      enabled: true
      mountPath: /unraid
      size: 1Gi
  deviceList:
    - name: qbittorrent-downloads
      enabled: true
      hostPath: /home/torrents
      readOnly: true
  podSecurityContext:
    runAsGroup: 568
    runAsUser: 568
  securityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
  service:
    ftpport:
      enabled: false
      ports:
        ftpport:
          enabled: true
          port: 2121
          protocol: TCP
          targetPort: 2121
    main:
      ports:
        main:
          port: 8888
          protocol: HTTP
          targetPort: 8888
    passiveports:
      enabled: false
      ports:
        passiveports:
          enabled: true
          port: 50000
          protocol: TCP
          targetPort: 50000
    sftpport:
      enabled: true
      ports:
        sftpport:
          enabled: true
          port: 2222
          protocol: TCP
          targetPort: 2222
    webdavport:
      enabled: false
      ports:
        webdavport:
          enabled: true
          port: 10080
          protocol: TCP
          targetPort: 10080

  portal:
    enabled: true

  podOptions:
    hostNetwork: true
