apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - git:
        repoURL: https://github.com/maxime1907/argocd-krysantem.git
        revision: HEAD
        files:
          - path: "cert-manager/**.yml"
  template:
    metadata:
      name: '{{name}}-cert-manager'
    spec:
      project: default
      source:
        helm:
          releaseName: cert-manager
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://github.com/bitnami/charts.git
        targetRevision: HEAD
        path: "bitnami/cert-manager"

      destination:
        server: '{{address}}'
        namespace: cert-manager

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
